sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer

language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress"
        - COMPOSER_FLAGS=""

stages:
    - Static Code Analysis
    - Test

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

    # Composer: boost installation
    - composer global show -ND 2>&1 | grep "hirak/prestissimo" || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

install:
    - composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit

jobs:
    include:
        -
            stage: Static Code Analysis
            php: 7.2
            script:
                - composer validate --strict || travis_terminate 1
                - composer normalize --dry-run || travis_terminate 1
                - vendor/bin/phpmd src,tests text phpmd.xml || travis_terminate 1
                - vendor/bin/php-cs-fixer fix --diff --dry-run -v || travis_terminate 1
